# Generated by Django 5.1.1 on 2024-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_app', '0003_alter_student_email_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(),
        ),
    ]
